eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
logging:
  level:
  #给指定的Feign日志
    com.forezp.config.MyConfiguration: debug
#第一次访问超时的解决方案
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix.command.default.execution.timeout.enabled: false
feign.hystrix.enabled: false #禁用hystrix