eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-ribbon

#配置文件的方式设置Ribbon的负载均衡策略
SERVICE-HI:
  ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NIWSServerListClassName: com.netflix.loadbalancer.RandomRule