eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8770
spring:
  application:
    name: service-ribbon

#配置文件的方式设置Ribbon的负载均衡策略
SERVICE-HI:
  ribbon:
#    ReadTimeout: 60000
#    ConnectTimeout: 60000
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    NIWSServerListClassName: com.netflix.loadbalancer.RandomRule
#    没有注册中心时候单独使用ribbon访问服务
    listOfServers: http://192.168.1.4:8763,http://192.168.1.4:8765
#禁用eureka
ribbon:
  eureka:
   enabled: false